feedback: #UPS-4345
cultuurnet/uitpas-balie-frontend pull request #3
Opened 2023-10-20 07:43 UTC by d-vostrikov

### Added

- A little bit of padding to the list for mobile devices.
- The ability to select a previously used counter, which will appear at the top of the list in a separate category.
- A search input field to quickly look up counters. 
- A loading spinner for when the data is being fetched.
- A button that allows you to sign in using another account if the current account you're signed into has no counters for you to choose from. 

### Changed

- Translation punctuation
- Refactored counter store to use generic local storage utils
- Merged `useActiveCounter` & `useSetActiveCounter` into one hook -> `useCounter`

### Removed

### Fixed

- Not being able to scroll when there are many counters displayed.

---
Ticket: https://jira.publiq.be/browse/UPS-4345

2023-10-20 08:12 UTC, d-vostrikov commented
Screenshots as requested by @khauman 
![image](https://github.com/cultuurnet/uitpas-balie-frontend/assets/147693297/ef04ad47-3286-473d-9a2b-59db630692da)
![image](https://github.com/cultuurnet/uitpas-balie-frontend/assets/147693297/b76dc1c4-2376-424e-b489-a584d2ba034a)
![image](https://github.com/cultuurnet/uitpas-balie-frontend/assets/147693297/b38aa816-24c0-4dcb-b497-d43c6d884c4d)
![image](https://github.com/cultuurnet/uitpas-balie-frontend/assets/147693297/87d1100c-c61b-442e-a42c-fb4e49c578d4)
![image](https://github.com/cultuurnet/uitpas-balie-frontend/assets/147693297/4f0ef64d-7a9f-47be-b25e-0b9b80a47be6)
![image](https://github.com/cultuurnet/uitpas-balie-frontend/assets/147693297/0fdc6838-74b3-4a16-9729-4cf291128b05)

2023-10-23 11:35 UTC, khauman commented on src/feature-counter/components/CounterPicker.tsx
> +  // TODO port loader from ng app?, Error message?
dit is precies toch een grote en complex component, is het mogelijk om deze toch in kleinere stukjes op te splitsen?

2023-10-23 11:35 UTC, khauman commented on src/feature-counter/components/CounterPicker.tsx
> +            sx={{
deze styling zie ik in deze component als 2x, best ook apart trekken naar een component

2023-10-23 13:18 UTC, hirviid requested changes

2023-10-23 13:18 UTC, hirviid commented on src/feature-counter/components/SelectCounterPage.tsx
> +                placeholder="Zoek balie"
Hardcoded string, kan je die naar common.json verplaatsen?

2023-10-23 13:18 UTC, hirviid commented on src/feature-counter/components/CounterPicker.tsx
> +  const renderData = () => {
zoals kevin zegt, best opsplitsen naar kleinere componenten. Render functies gaan trouwens wat in tegen de standard practice in React. Interessant artikel daarover: https://overreacted.io/react-as-a-ui-runtime/#inversion-of-control . Dus ipv bv `renderSearchFilteredData`: Een component `<SearchFilteredData />` waar je de data als props meegeeft.

2023-10-23 13:27 UTC, hirviid requested changes

2023-10-23 13:27 UTC, hirviid commented on src/feature-counter/components/SelectCounterPage.tsx
> +  const [dataAvailable, setDataAvailable] = useState<boolean>(false);
Ik zou de data in deze page ophalen en doorgeven aan CounterPicker, ipv de data op te halen in CounterPicker en dan in deze een extra state te moeten bijhouden dat de data beschikbaar is. Op die manier 
- kan de CounterPicker "dommer" gehouden worden: Je geeft ineens de gefilterde lijst van counters mee, de responsibility van de CounterPicker is dan enkel het renderen van een lijst van counters en het selecteren/activeren van een counter.
- heb je een makkelijkere te volgen flow: Data wordt opgehaald bovenaan de tree, en in combinatie met een filter doorgegeven naar beneden (en dus een useState minder in deze component en een useEffect minder in de CounterPicker component).

2023-10-23 13:27 UTC, hirviid commented on src/lib/utils/localStorageUtils.ts
> +export const storeData = <T>(key: string, data: T): void => {
Kan je eens nakijken hoe dit in de Angular app gedaan wordt? We hebben het probleem dat de Java FX browser geen localStorage heeft, dus dit gaat niet werken in de desktop app. Het kan zijn dat dit in de Silex PHP app wordt bijgehouden, in dat geval zullen we dat even moeten bespreken met Publiq hoe ze willen dat we dit oplossen.

2023-10-24 12:31 UTC, d-vostrikov commented on src/lib/utils/localStorageUtils.ts
> +export const storeData = <T>(key: string, data: T): void => {
In de Angular app wordt er de backend gebruikt om de current active counter te setten & ophalen. In de nieuwe heb ik geen endpoints gevonden die dat doen. Daar zouden we iets voor moeten voorzien, eventueel in de JavaFx browser zelf iets om dat te ondersteunen? 
  
De laatst gebruikte counter wordt wel in een cookie opgehaald though :thinking:

2023-10-30 13:03 UTC, merged