feat: make nav menu mobile friendly
cultuurnet/uitpas-balie-frontend pull request #4
Opened 2023-10-23 10:51 UTC by d-vostrikov

Refs: #UPS-4679

2023-10-23 11:29 UTC, khauman commented on src/layouts/components/Navbar.tsx
> +  function handleWindowResize() {
```
  const  handleWindowResize = useCallback(()=> { ... }, [])
```
(en deze kan je dan best ook boven de useEffect zetten)

2023-10-23 11:29 UTC, khauman commented on src/layouts/components/Navbar.tsx
> +  }, []);
```
useEffect(()=> { ... }, [handleWindowResize])
```

2023-10-23 11:29 UTC, khauman commented on src/lib/utils/hooks/useMenu.ts
> +  const [isOpen, setOpen] = useState<boolean>(false);
deze `<boolean>` is niet expliciet nodig, maar het is niet "fout"

2023-10-23 11:29 UTC, khauman commented on src/layouts/Layout.tsx
> +      {renderNavBar && <Navbar userInfo={userInfo!} counter={counter!} />}
userInfo of counter kan 'falsey' zijn, renderNavBar is true als 1 van de 2 'true' zijn

ik neem aan dat de navbar enkel getoond wordt als beide 'true' zijn? dan kan je best op lijn 15 de check aanpassen.

2023-10-23 13:33 UTC, hirviid requested changes

2023-10-30 13:05 UTC, hirviid approved these changes

2023-10-30 15:02 UTC, merged